### ISSUE TITLE
Getting Error

### ISSUE THREAD

**Issue by patelsanket864** [driemworks/agatha#4]
(pretick) C:\Users\dell\Desktop\agatha-master\agatha-master\examples>python app.py
Using TensorFlow backend.
Found 3 tickers to check
START - F - 0/3
An error occurred for ticker F
Ran out of input
START - AAPL - 1/3
An error occurred for ticker AAPL
Ran out of input
START - GE - 2/3
An error occurred for ticker GE
Ran out of input
[]
found 0 candidates

**Comment by flyingbrike** [comment]
same here i think

erik@stmserver:~/agatha/examples$ python3 app.py
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(app.py:4952): Gdk-CRITICAL **: 17:05:28.979: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Using TensorFlow backend.
Found 3 tickers to check
START - F - 0/3
An error occurred for ticker F
Ran out of input
START - AAPL - 1/3
An error occurred for ticker AAPL
Ran out of input
START - GE - 2/3
An error occurred for ticker GE
Ran out of input
[]
found 0 candidates
Traceback (most recent call last):
  File "app.py", line 85, in <module>
    readCandidatePlots()
  File "app.py", line 36, in readCandidatePlots
    for filename in os.listdir('./candidates'):
FileNotFoundError: [Errno 2] No such file or directory: './candidates'
